/**
 * 全国机场/城市数据
 * code: 机场代码
 * city: 城市中文名
 */
const AIRPORTS = [
  { code: "AAT", city: "阿勒泰" },
  { code: "AKA", city: "安康" },
  { code: "AQG", city: "安庆" },
  { code: "AOG", city: "鞍山" },
  { code: "AVA", city: "安顺" },
  { code: "BSD", city: "保山" },
  { code: "PAV", city: "白山" },
  { code: "BHY", city: "北海" },
  { code: "BJS", city: "北京" },
  { code: "BPX", city: "日喀则" },
  { code: "CGQ", city: "长春" },
  { code: "CGO", city: "郑州" },
  { code: "CSX", city: "长沙" },
  { code: "CTX", city: "赤峰" },
  { code: "CHW", city: "朝阳" },
  { code: "CIF", city: "赤峰" },
  { code: "CZX", city: "常州" },
  { code: "CKG", city: "重庆" },
  { code: "DAX", city: "达州" },
  { code: "DLC", city: "大连" },
  { code: "DLU", city: "大理" },
  { code: "DAT", city: "大同" },
  { code: "DDG", city: "丹东" },
  { code: "DIG", city: "德宏" },
  { code: "DOY", city: "东营" },
  { code: "DNH", city: "敦煌" },
  { code: "ENH", city: "恩施" },
  { code: "FUG", city: "阜阳" },
  { code: "FOC", city: "福州" },
  { code: "KOW", city: "赣州" },
  { code: "GOQ", city: "格尔木" },
  { code: "GHN", city: "广汉" },
  { code: "CAN", city: "广州" },
  { code: "GYS", city: "广元" },
  { code: "KWL", city: "桂林" },
  { code: "KWE", city: "贵阳" },
  { code: "HAK", city: "海口" },
  { code: "HLD", city: "海拉尔" },
  { code: "HMI", city: "哈密" },
  { code: "HRB", city: "哈尔滨" },
  { code: "HGH", city: "杭州" },
  { code: "HZG", city: "汉中" },
  { code: "HFE", city: "合肥" },
  { code: "HEK", city: "黑河" },
  { code: "HTN", city: "和田" },
  { code: "HKG", city: "香港" },
  { code: "TXN", city: "黄山" },
  { code: "HYN", city: "台州" },
  { code: "JZH", city: "九寨沟" },
  { code: "JGN", city: "嘉峪关" },
  { code: "JIL", city: "吉林" },
  { code: "TNA", city: "济南" },
  { code: "JNG", city: "济宁" },
  { code: "JDZ", city: "景德镇" },
  { code: "JHG", city: "西双版纳" },
  { code: "JJN", city: "泉州" },
  { code: "JMU", city: "佳木斯" },
  { code: "JIU", city: "九江" },
  { code: "JZH", city: "九寨黄龙" },
  { code: "KHG", city: "喀什" },
  { code: "KRL", city: "库尔勒" },
  { code: "KMG", city: "昆明" },
  { code: "KCA", city: "库车" },
  { code: "LHW", city: "兰州" },
  { code: "LXA", city: "拉萨" },
  { code: "LYG", city: "连云港" },
  { code: "LJG", city: "丽江" },
  { code: "LYI", city: "临沂" },
  { code: "LZH", city: "柳州" },
  { code: "LCX", city: "龙岩" },
  { code: "LUM", city: "芒市" },
  { code: "LYA", city: "洛阳" },
  { code: "MFM", city: "澳门" },
  { code: "MXZ", city: "梅州" },
  { code: "MIG", city: "绵阳" },
  { code: "MDG", city: "牡丹江" },
  { code: "KHN", city: "南昌" },
  { code: "NAO", city: "南充" },
  { code: "NKG", city: "南京" },
  { code: "NNG", city: "南宁" },
  { code: "NGB", city: "宁波" },
  { code: "PZI", city: "攀枝花" },
  { code: "IQM", city: "且末" },
  { code: "TAO", city: "青岛" },
  { code: "IQN", city: "庆阳" },
  { code: "SHP", city: "秦皇岛" },
  { code: "NDG", city: "齐齐哈尔" },
  { code: "JJN", city: "晋江" },
  { code: "SYX", city: "三亚" },
  { code: "SHA", city: "上海" },
  { code: "PVG", city: "上海" },
  { code: "SWA", city: "汕头" },
  { code: "SHE", city: "沈阳" },
  { code: "SJW", city: "石家庄" },
  { code: "SZV", city: "苏州" },
  { code: "TCG", city: "塔城" },
  { code: "TSN", city: "天津" },
  { code: "TGO", city: "通辽" },
  { code: "TEN", city: "铜仁" },
  { code: "WEF", city: "潍坊" },
  { code: "WEH", city: "威海" },
  { code: "WNZ", city: "温州" },
  { code: "WUH", city: "武汉" },
  { code: "HLH", city: "乌兰浩特" },
  { code: "URC", city: "乌鲁木齐" },
  { code: "WUX", city: "无锡" },
  { code: "WUS", city: "武夷山" },
  { code: "WUZ", city: "梧州" },
  { code: "XMN", city: "厦门" },
  { code: "XIY", city: "西安" },
  { code: "XIC", city: "西昌" },
  { code: "XNN", city: "西宁" },
  { code: "XUZ", city: "徐州" },
  { code: "ENY", city: "延安" },
  { code: "YNZ", city: "盐城" },
  { code: "YTY", city: "扬州" },
  { code: "YNT", city: "烟台" },
  { code: "YBP", city: "宜宾" },
  { code: "YIH", city: "宜昌" },
  { code: "INC", city: "银川" },
  { code: "YIN", city: "伊宁" },
  { code: "YIW", city: "义乌" },
  { code: "UYN", city: "榆林" },
  { code: "YCU", city: "运城" },
  { code: "ZHA", city: "湛江" },
  { code: "ZAT", city: "昭通" },
  { code: "CGO", city: "郑州" },
  { code: "ZHY", city: "中卫" },
  { code: "HSN", city: "舟山" },
  { code: "ZUH", city: "珠海" },
  { code: "ZYI", city: "遵义" },
  { code: "SZX", city: "深圳" },
  { code: "CTU", city: "成都" },
  { code: "PEK", city: "北京" },
  { code: "PKX", city: "北京" }
];

const CITY_MAP = new Map(AIRPORTS.map((a) => [a.code, a.city]));

function getCityByCode(code) {
  if (!code) return "";
  return CITY_MAP.get(code.toUpperCase()) || code;
}

module.exports = {
  AIRPORTS,
  getCityByCode
};
